### ISSUE TITLE
Running uninstallPackage twice fails

### ISSUE THREAD

**Issue by ndorotte** [fundacionjala/enforce-gradle-plugin#235]
When I try running the uninstallPackage task twice in a row with version 1.0.5, I get the following error the second time.

Command:
<pre>
$ gradle uninstallPackage -Ppkg.namespace=pros_q2w -PcredentialId=20demo.com
</pre>

Output:
<pre>
:uninstallPackage
___________________________________________  
	Username: ndorotte@20demo.com           
	Login type: login
___________________________________________  

Verifying installed package 'pros_q2w' ...
Starting retrieve...
Waiting for retrieve result...
Retrieve result completed
Failed execute task
:uninstallPackage FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':uninstallPackage'.
> java.lang.ClassCastException: org.apache.xerces.parsers.XIncludeAwareParserConfiguration cannot be cast to org.apache.xerces.xni.parser.XMLParserConfiguration

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 17.315 secs
</pre>

**Comment by marcocdlv** [comment]
Hi @ndorotte,

This bug was fixed at 1.1.2 version, Could you review that, please?

The best regards

**Comment by ndorotte** [comment]
I still get the same error. Here's the version of Java and Gradle I'm using if that helps

<pre>
$ java -version
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)

$ ./gradlew -version
------------------------------------------------------------
Gradle 2.3
------------------------------------------------------------

Build time:   2015-02-16 05:09:33 UTC
Build number: none
Revision:     586be72bf6e3df1ee7676d1f2a3afd9157341274

Groovy:       2.3.9
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.8.0_31 (Oracle Corporation 25.31-b07)
OS:           Mac OS X 10.10.5 x86_64
</pre>

**Comment by marcocdlv** [comment]
This happens with version 1.1.2?

**Comment by ndorotte** [comment]
Yep. After some Googling it seems that it may be due to a conflict with the version of Xerces being used.
We have a plugin that uses version 2.11.0 but it looks like Gradle depends on version 2.9.1.

I'm not sure if Enforce depends on it, and if it does which version it needs.

**Comment by ndorotte** [comment]
I updated to the latest version of Gradle and download-task (one of our dependencies) and the issue seems to be gone for now.

You can close this issue. I'll reopen it if needed.

Thanks!

**Comment by marcocdlv** [comment]
You are welcome
Regards
